# Generated by Django 2.2.3 on 2020-02-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus', 'two_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthstate',
            name='pub_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
