# Generated by Django 2.2.3 on 2020-02-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus_defend', 'one_init'),
    ]

    operations = [
        migrations.CreateModel(
            name='Healthstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state',models.IntegerField(choices=[(1, '良好'), (2, '疑似'), (3, '确诊')], default='良好', verbose_name='身体健康状态')),
                ('temp', models.CharField(max_length=50, verbose_name='体温')),
                ('place', models.CharField(max_length=60, verbose_name='所在地区')),
            ],
        ),
        migrations.DeleteModel(
            name='Health',
        ),
    ]
